spring:
  threads:
    virtual:
      enabled: true


management:
  #endpoint:
    #health:
      #show-details: always
  health:
    redis:
      enabled: false

server:
  port: 8080

proxy:
  max-body-size: 16384 # 16 KB
  backend:
    uri: "http://localhost:8081"
  guardian:
    security:
      allowed-paths:
        - /test
        - /actuator/health
        - /api/v1  # This will allow /api/v1/users, /api/v1/orders, etc.



